### ISSUE TITLE
Clean-up Shelley Networking Handshake Mini Protocol

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/rust-cardano-ouroboros-network#1]
Clean-up _Cardano Shelley Networking_ **Handshake Mini Protocol** as described in 
[The Shelley Networking Protocol version 1.0.0 rev 47](https://github.com/2nd-Layer/rust-cardano-ouroboros-network/files/5612428/2020-0ct-05_IOG_The_Shelley_Networking_Protocol_v1.0_rev47.pdf) Section 2.10:
  - [Haskell Reference Implementation](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network-framework/src/Ouroboros/Network/Protocol/Handshake.hs)
  - [Rust Reference Implementation](https://github.com/AndrewWestberg/cncli/blob/develop/src/nodeclient/protocols/handshake_protocol.rs)

**Comment by mark-stopka** [comment]
Beware: [[DOCS] Links to implemented mini-protocols are obsolete](https://github.com/input-output-hk/ouroboros-network/issues/2780)

**Comment by mark-stopka** [comment]
@pavlix does handshake protocol still needs some work, or can this one be closed?

**Comment by mark-stopka** [comment]
@pavlix ping? If there are tasks left for this issue, please provide a short bullet-point list, if not, let's close it.

**Comment by pavlix** [comment]
@mark-stopka  I guess the handshake code is good for now. Thanks goes to @AndrewWestberg . We also have a server-side stub (just a fixed string, not a real implementation). I think we're done with the initial clean-up.
