### ISSUE TITLE
[FR] Channel needs to have a disconnect() or close() method

### ISSUE THREAD

**Issue by AndrewWestberg** [2nd-Layer/rust-cardano-ouroboros-network#21]
User of `Channel` should have the ability to gracefully close the connection. For example, after a ping command where all we do is run Handshake and exit, we should be nice to the remote server and gracefully shut down the socket.

See: https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.shutdown

**Comment by pavlix** [comment]
After a discussion with @AndrewWestberg off GitHub I'm closing this with the following note:

```
The connection will be closed when the value is dropped. The reading and writing portions of the connection can also be shut down individually with the shutdown method.
```

All you need to close the TCP connection is to drop the `tcp::mux::Channel` struct e.g. by defining it inside a block that designates its lifetime.
