### ISSUE TITLE
Clean-up Cardano Shelley Networking Chain Synchronisation Mini Protocol

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/rust-cardano-ouroboros-network#3]
Clean-up _Cardano Shelley Networking_ **Chain Synchronisation Mini Protocol** as described in 
[The Shelley Networking Protocol version 1.0.0 rev 47](https://github.com/2nd-Layer/rust-cardano-ouroboros-network/files/5612428/2020-0ct-05_IOG_The_Shelley_Networking_Protocol_v1.0_rev47.pdf) Section 2.6:
  - [Haskell Reference Implementation](https://github.com/input-output-hk/ouroboros-network/tree/master/ouroboros-network/src/Ouroboros/Network/Protocol/ChainSync)
  - [Rust Reference Implementation](https://github.com/AndrewWestberg/cncli/blob/develop/src/nodeclient/protocols/chainsync_protocol.rs)

**Comment by mark-stopka** [comment]
Related to #20, see https://github.com/2nd-Layer/rust-cardano-ouroboros-network/issues/20#issuecomment-745108277

**Comment by pavlix** [comment]
I am looking into the `chainsync` code. There is a distinction between two protocol modes that doesn't reflect the protocol specification. It has already been modified as part of moving out SQL and PoolTool parts.

We are moving towards an implementationt that:

- Saves blocks *if* there is a `Storage` configured, see `examples/sqlite.rs`.
- Notifies about reaching the tip *if* there is a `Notifier` configured, see `examples/pooltool.rs`.

That way you can choose to store the blocks and/or notify about reaching the tip.

My question for @AndrewWestberg is:

Why do we invalidate the intersect when we have not reached the tip yet? Shouldn't we just keep going until we reach the tip?

```
match self.mode {
    Mode::Sync => { self.save_block(msg_roll_forward).unwrap(); }
    Mode::SendTip => {
        /* Last MsgRollForward? */
        if msg_roll_forward.slot_number == tip.slot_number && msg_roll_forward.hash == tip.hash {
            match &mut self.notify {
                Some(notifier) => {
                    notifier.notify_tip(tip, msg_roll_forward);
                }
                None => {}
            }
        /* Why is that? */
        } else {
            self.tip_to_intersect = Some(tip);
            self.is_intersect_found = false;
        }
    }
}
```

**Comment by AndrewWestberg** [comment]
In SendTip mode, we don't care about syncing the chain. We just want the
tip information to notify pooltool that the node is on the tip. We need the
whole header info to send them and not just the tip info. To accomplish
this, we send an Intersect and start syncing at the tip of the blockchain.
We don't care about any blocks in between in this mode.

**Comment by mark-stopka** [comment]
We have to preserve the functionality, however we may refactor it somehow if it makes sense... see justification below...
![image](https://user-images.githubusercontent.com/18139116/103101143-791b7700-4616-11eb-9f96-4c741ecb9edb.png)

**Comment by pavlix** [comment]
@mark-stopka SQL is gone, Pooltool is gone. All of that is now handled by cncli and shown in examples. We might want to revisit this code as part of server side implementation but for now I guess we're done with the initial clean-up task.
