### ISSUE TITLE
Pipelined cbor messages fail to parse

### ISSUE THREAD

**Issue by AndrewWestberg** [2nd-Layer/rust-cardano-ouroboros-network#51]
in tcp.rs: 165, we read the payload header from the server. In most cases, we receive a length value for one cbor message. Every cbor message from the node has the outer layer as a cbor array.  In some cases, the node will pipeline cbor messages and give us several cbor arrays even though they have a single header payload.  

Here is an example of what the payload looks like when we were pipelined a `msgAwaitReply` followed immediately by a `msgRollBackward`

```
81018303821a014e760f5820c65e68031874fa494e2d43627a67a96d1c443522ff6b3f2f92ff04ae62ae843a82821a014e761058207c3bc2fb2d3d8c8a9c12beed5e3ae071532b2b13ba6db702e2f6b23f928e40b41a0051a325
```
```
8101 -> [1] ==  msgAwaitReply
8303821a014e760f5820c65e68031874fa494e2d43627a67a96d1c443522ff6b3f2f92ff04ae62ae843a82821a014e761058207c3bc2fb2d3d8c8a9c12beed5e3ae071532b2b13ba6db702e2f6b23f928e40b41a0051a325 -> [3, [21919247, h'C65E68031874FA494E2D43627A67A96D1C443522FF6B3F2F92FF04AE62AE843A'], [[21919248, h'7C3BC2FB2D3D8C8A9C12BEED5E3AE071532B2B13BA6DB702E2F6B23F928E40B4'], 5350181]]
```

This results in:
```
Feb 16 14:25:39 papa cncli-sendtip[3658636]:  2021-02-16T14:25:39.304Z ERROR cardano_ouroboros_network::protocols::chainsync   > cbor decode error!: trailing data at offset 3, hex: 81018303821a014e760f5820c65e68031874fa494e2d43627a67a96d1c443522ff6b3f2f92ff04ae62ae843a82821a014e761058207c3bc2fb2d3d8c8a9c12beed5e3ae071532b2b13ba6db702e2f6b23f928e40b41a0051a325
```

Our code in tcp.rs is making the assumption that only a single cbor message will be in a payload and then fails to parse when we call `protocol.receive_data(payload)` because it sees it as "extra data".

We need to find a way to efficiently split payloads into separate messages.

**Comment by pavlix** [comment]
Does that mean the length may actually be a sum of lengths of multiple cbor messages? I was long thinking about switching the miniprotocols from blob based interface to cbor based interface. Of course it isn't the only way to handle that but if the data format is guaranteed, then it sounds just sensible.

**Comment by AndrewWestberg** [comment]
> Does that mean the length may actually be a sum of lengths of multiple cbor messages? I was long thinking about switching the miniprotocols from blob based interface to cbor based interface. Of course it isn't the only way to handle that but if the data format is guaranteed, then it sounds just sensible.

Yes. The length is actually the length of the entire payload which could include back to back cbor messages as long as they are destined for the same mini-protocol (share the same header)
