### ISSUE TITLE
[FEAT] Add MARY protocol version to handshake protocol

### ISSUE THREAD

**Issue by AndrewWestberg** [2nd-Layer/rust-cardano-ouroboros-network#58]
If we pass 0x06 as a MsgProposeVersion and the remote node is running 1.26.0 or higher, we will get back a MsgAcceptVersion with 0x06 in the payload. 

The difference between 0x05 and 0x06 is that the TxSubmissionProtocol has its starting agency flipped around the same as all the other protocols. In 0x05, the remote server started with agency so we had to spin up TxSubmissionProtocol right away to listen for messages from the server. In 0x06, when doing regular syncing with the node, we can not connect TxSubmissionProtocol at all since the server will be waiting on us forever to send something.

When doing a sync, we should update to support 0x06 and just omit adding TxSubmissionProtocol if the server responds with 0x06.

**Comment by mark-stopka** [comment]
@pavlix can you scope the required work in terms of effort in MH?

**Comment by mark-stopka** [comment]
@pavlix ping?

**Comment by mark-stopka** [comment]
> @pavlix ping?

Can you quote me the required statements of works?
