### ISSUE TITLE
[FEAT] Minimal version of the protocol should come from the crate consumer, not from the library itself

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/rust-cardano-ouroboros-network#64]
I think the minimal version of the protocol should come from the crate consumer, not from the library itself, what do you think @AndrewWestberg?

_Originally posted by @mark-stopka in https://github.com/2nd-Layer/rust-cardano-ouroboros-network/pull/61#issuecomment-813709827_

**Comment by pavlix** [comment]
This looks like a call for a minor API redesign to prepare for future extensibility.

**Comment by mark-stopka** [comment]
@AndrewWestberg, as per your Twitter reply, you consider it rather a step-back, right? I will close the issue, if you can confirm that you as a crate consumer consider it undesirable until such time when some other initiative may need it.

**Comment by AndrewWestberg** [comment]
If the consumer is providing the min protocol version, then we need to keep the library compatible with all of those old versions. This will likely become a lot of tech debt especially as we enter the P2P era. I think we should keep pushing the min version up inside the library at least until the protocol stabilizes after goguen and P2P. That way, we don't carry a lot of tech debt.

**Comment by mark-stopka** [comment]
Makes sense, closing for now, and I'll keep an eye on how is the situation evolving!
